Yooper.Admin/Controllers/LicenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yooper.DTO;
using Yooper.UOW;
using Yopper.Common;

namespace Yooper.Admin.Controllers
{
    [SecurityLayer]
    public class LicenseController : Controller
    {
        IUnitofWork _uow;
        public LicenseController(IUnitofWork uow)
        {
            _uow = uow;
        }
        // GET: License
        public ActionResult Index()
        {
            var model = _uow.Admin.GetUsers().Where(x=> !string.IsNullOrEmpty(x.SecretKey));
            return View(model);
        }

        public ActionResult GenerateLicense(long? Id)
        {
            try
            {
                var __model = new GenerateLicenseVM();
                var obj = _uow.Admin.GetUsers().Where(x => x.Id == Id).Select(x=>new GenerateLicenseVM() {
                    UserId= x.Id,
                    LicenseExpiryDate= x.LicenseExpiryDate,
                    NumberOfLogin= x.Limit,
                    SecretKey= x.SecretKey
                }).FirstOrDefault();
                if (obj!=null)
                {
                    __model = obj;
                    ViewBag.users = _uow.Admin.GetUsers().Where(x => x.Id== __model.UserId && !x.Block);
                }
                else
                {
                    ViewBag.users = _uow.Admin.GetUsers().Where(x => string.IsNullOrEmpty(x.SecretKey) && !x.Block);
                }
                
                return View(__model);
            }
            catch (YooperException ex)
            {
                throw ex;
            }
        }
        [HttpPost]
        public ActionResult GenerateLicense(GenerateLicenseVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _uow.Admin.GenerateLicenseKey(model.UserId, model.SecretKey, model.NumberOfLogin.GetValueOrDefault(), model.LicenseExpiryDate.GetValueOrDefault());
                }
                return RedirectToAction("Index");
            }
            catch (YooperException ex)
            {
                throw ex;
            }
        }



        public ActionResult CreateLicense()
        {
            return Json(new { Data = Guid.NewGuid().ToString() }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Restart(long Id)
        {
            _uow.Admin.RestartUserApplication(Id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

Yooper.Admin/Views/License/GenerateLicense.cshtml
@using Yooper.DTO;
@model Yooper.DTO.GenerateLicenseVM
@{
    ViewBag.Title = "GenerateLicense";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var breadcrumb = new List<BreadCrumb>()
{
new BreadCrumb() {Title="License Management",Link="/License/Index"},
new BreadCrumb() {Title="Generate License",Link=""}
};
    ViewBag.breadcrumb = breadcrumb;
    List<SelectListItem> dropdown = new List<SelectListItem>();
    var user = ViewBag.users as IQueryable<Yooper.DTO.User>;
    foreach (var item in user)
    {
        dropdown.Add(new SelectListItem { Text = item.Username, Value = item.Id.ToString() });
    }
}

<div class="portlet box blue-hoki">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-key"></i>Generate License Form
        </div>
        <div class="tools">
            <a href="" class="collapse" data-original-title="" title=""> </a>
        </div>
    </div>
    <div class="portlet-body form" style="display: block">
        <!-- BEGIN FORM-->
        @using (Html.BeginForm("GenerateLicense", "License", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-actions top">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn green">Submit</button>
                        <a href="@Url.Action("Index","License")" class="btn default">Cancel</a>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">User</label>
                    <div class="col-md-4">
                        <div class="input-icon right">
                            @Html.DropDownListFor(x => x.UserId, dropdown, "--select user--", new { @class = "form-control drp-user" })
                        </div>
                        <span style="color:red">@Html.ValidationMessageFor(x => x.UserId)</span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-3 control-label">Secret Key</label>
                    <div class="col-md-4">
                        <div class="input-icon right">
                            <i class="fa fa-user-secret"></i>
                            @Html.TextBoxFor(x => x.SecretKey, new { @class = "form-control", id = "SecretKey", placeholder = "Enter Secret key here." })
                            <button type="button" onclick="GenerateSecretKey()" class="btn green btn-xs">Generate Secret Key</button>
                        </div>
                        <span style="color:red">@Html.ValidationMessageFor(x => x.SecretKey)</span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-3 control-label">License Expiry Date</label>
                    <div class="col-md-4">
                        <div class="input-icon right">
                            <i class="fa fa-calendar"></i>
                            @Html.TextBoxFor(x => x.LicenseExpiryDate, new { @class = "form-control", id = "license", placeholder = "Enter Secret key here." })
                        </div>
                        <span style="color:red">@Html.ValidationMessageFor(x => x.LicenseExpiryDate)</span>
                    </div>
                </div>


                <div class="form-group">
                    <label class="col-md-3 control-label">Number of login</label>
                    <div class="col-md-4">
                        <div class="input-icon right">
                            <i class="fa fa-lock"></i>
                            @Html.TextBoxFor(x => x.NumberOfLogin, new {type="number", @class = "form-control", placeholder = "Add number of logins" })
                        </div>
                        <span style="color:red">@Html.ValidationMessageFor(x => x.NumberOfLogin)</span>
                    </div>
                </div>
            </div>
        }
        <!-- END FORM-->
    </div>
</div>


@section script{
    <script type="text/javascript">
        function GenerateSecretKey() {
            jQuery.ajax({
                url: '/License/CreateLicense',
                method: 'GET',
                success: function (res) {
                    console.log(res);
                    $('#SecretKey').val(res.Data).focus();
                    toastr["success"]("Secret key generated successfully.", "Success")
                },
                error: function (err) {
                    console.log(err);
                }
            });
        }
        var date = new Date();
        date.setDate(date.getDate());
        $('#license').datepicker({
            rtl: App.isRTL(),
            orientation: "left",
            autoclose: true,
            startDate: date
        });
        $('.drp-user').select2();
    </script>
}

Yooper.Admin/Views/License/Index.cshtml
@using Yooper.DTO
@model IQueryable<Yooper.DTO.User>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var breadcrumb = new List<BreadCrumb>()
{
new BreadCrumb() {Title="License Management",Link="/License/Index"}
};
    ViewBag.breadcrumb = breadcrumb;
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-briefcase font-dark hide"></i>
                    <span class="caption-subject font-hide bold uppercase">License Management</span>
                </div>
            </div>
            <div class="portlet-body">
                <a title="Assign new secret key to user." href="@Url.Action("GenerateLicense","License")" class="btn btn-icon-only green">
                    <i class="fa fa-plus"></i>
                </a>
                @*@Html.MVCGrid("UserGrid")*@
                <table class="table table-striped table-bordered table-hover table-checkable order-column dataTable no-footer" id="tbl_users">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Secret Key</th>
                            <th>Expiry</th>
                            <th>No. of logins</th>
                            <th>Action</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int count = 1;   }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@count</td>
                                <td>@item.Name</td>
                                <td>@item.Username</td>
                                <td>@item.SecretKey</td>
                                <td><span class="btn btn-danger">@item.LicenseExpiryDate.GetValueOrDefault().ToString("MMM dd, yyyy")</span></td>
                                <td><span class="btn btn-danger">@item.Limit</span></td>
                                <td>
                                    <button class="btn btn-primary btn-xs" title="restart user application" onclick="restart('@item.Id')"><i class="fa fa-repeat"></i></button>
                                </td>
                                <td>
                                    <a title="Generate/renew secret keys" href="@Url.Action("GenerateLicense","License",new {Id= item.Id })" class="btn btn-icon-only blue">
                                        <i class="fa fa-key"></i>
                                    </a>
                                </td>
                            </tr>
                            count++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


@section script{
    <script type="text/javascript">
        $('#tbl_users').DataTable({
            'aoColumnDefs': [{
                'bSortable': false,
                'aTargets': [-1] /* 1st one, start by the right */
            }, {
                    'bSortable': false,
                    'aTargets': [-2] /* 1st one, start by the right */
                }]
        });

        function restart(id) {
            var confirmation = confirm('Are you sure you want to restart ?');

            if (confirmation === true) {
                $.ajax({
                    url: '/License/Restart?Id=' + id,
                    method: 'GET',
                    success: function (res) {
                        toastr["success"]('Application is restarted. ', 'Success');
                    },
                    error: function (err) {
                        console.log(err);
                    }
                });
            }
            
        }
    </script>
}